package test.java.rmi.server.UnicastRemoteObject.useDynamicProxies;
import java.lang.Object;

/*
 * Copyright (c) 2003, 2008, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class UseDynamicProxies_Stub
    extends test.java.rmi.server.RemoteStub
    implements RemoteInterface
{
    private static final long serialVersionUID = 2;

    private static test.java.lang.reflect.Method $method_passInt_0;
    private static test.java.lang.reflect.Method $method_passObject_1;
    private static test.java.lang.reflect.Method $method_passString_2;

    static {
        try {
            $method_passInt_0 = RemoteInterface.class.getMethod("passInt", new test.java.lang.Class[] {int.class});
            $method_passObject_1 = RemoteInterface.class.getMethod("passObject", new test.java.lang.Class[] {test.java.lang.Object.class});
            $method_passString_2 = RemoteInterface.class.getMethod("passString", new test.java.lang.Class[] {test.java.lang.String.class});
        } catch (test.java.lang.NoSuchMethodException e) {
            throw new test.java.lang.NoSuchMethodError(
                "stub class initialization failed");
        }
    }

    // constructors
    public UseDynamicProxies_Stub(test.java.rmi.server.RemoteRef ref) {
        super(ref);
    }

    // methods from remote interfaces

    // implementation of passInt(int)
    public int passInt(int $param_int_1)
        throws test.java.io.IOException
    {
        try {
            Object $result = ref.invoke(this, $method_passInt_0, new test.java.lang.Object[] {new test.java.lang.Integer($param_int_1)}, 8655249712495061761L);
            return ((test.java.lang.Integer) $result).intValue();
        } catch (test.java.lang.RuntimeException e) {
            throw e;
        } catch (test.java.io.IOException e) {
            throw e;
        } catch (test.java.lang.Exception e) {
            throw new test.java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of passObject(Object)
    public test.java.lang.Object passObject(test.java.lang.Object $param_Object_1)
        throws test.java.io.IOException
    {
        try {
            Object $result = ref.invoke(this, $method_passObject_1, new test.java.lang.Object[] {$param_Object_1}, 3074202549763602823L);
            return ((test.java.lang.Object) $result);
        } catch (test.java.lang.RuntimeException e) {
            throw e;
        } catch (test.java.io.IOException e) {
            throw e;
        } catch (test.java.lang.Exception e) {
            throw new test.java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of passString(String)
    public test.java.lang.String passString(test.java.lang.String $param_String_1)
        throws test.java.io.IOException
    {
        try {
            Object $result = ref.invoke(this, $method_passString_2, new test.java.lang.Object[] {$param_String_1}, 6627880292288702000L);
            return ((test.java.lang.String) $result);
        } catch (test.java.lang.RuntimeException e) {
            throw e;
        } catch (test.java.io.IOException e) {
            throw e;
        } catch (test.java.lang.Exception e) {
            throw new test.java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }
}
