package test.java.rmi.activation.Activatable.forceLogSnapshot;
/*
 * Copyright (c) 1998, 1999, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class ForceLogSnapshot_Stub
    extends test.java.rmi.server.RemoteStub
    implements ActivateMe
{
    private static final test.java.rmi.server.Operation[] operations = {
        new test.java.rmi.server.Operation("void crash()"),
        new test.java.rmi.server.Operation("void ping(int, java.lang.String)")
    };

    private static final long interfaceHash = -5865767584502007357L;

    private static final long serialVersionUID = 2;

    private static boolean useNewInvoke;
    private static test.java.lang.reflect.Method $method_crash_0;
    private static test.java.lang.reflect.Method $method_ping_1;

    static {
        try {
            test.java.rmi.server.RemoteRef.class.getMethod("invoke",
                new test.java.lang.Class[] {
                    test.java.rmi.Remote.class,
                    test.java.lang.reflect.Method.class,
                    test.java.lang.Object[].class,
                    long.class
                });
            useNewInvoke = true;
            $method_crash_0 = ActivateMe.class.getMethod("crash", new test.java.lang.Class[] {});
            $method_ping_1 = ActivateMe.class.getMethod("ping", new test.java.lang.Class[] {int.class, test.java.lang.String.class});
        } catch (test.java.lang.NoSuchMethodException e) {
            useNewInvoke = false;
        }
    }

    // constructors
    public ForceLogSnapshot_Stub() {
        super();
    }
    public ForceLogSnapshot_Stub(test.java.rmi.server.RemoteRef ref) {
        super(ref);
    }

    // methods from remote interfaces

    // implementation of crash()
    public void crash()
        throws test.java.lang.Exception
    {
        if (useNewInvoke) {
            ref.invoke(this, $method_crash_0, null, 8484760490859430950L);
        } else {
            test.java.rmi.server.RemoteCall call = ref.newCall((test.java.rmi.server.RemoteObject) this, operations, 0, interfaceHash);
            ref.invoke(call);
            ref.done(call);
        }
    }

    // implementation of ping(int, String)
    public void ping(int $param_int_1, test.java.lang.String $param_String_2)
        throws test.java.rmi.RemoteException
    {
        try {
            if (useNewInvoke) {
                ref.invoke(this, $method_ping_1, new test.java.lang.Object[] {new test.java.lang.Integer($param_int_1), $param_String_2}, -1519179153769139224L);
            } else {
                test.java.rmi.server.RemoteCall call = ref.newCall((test.java.rmi.server.RemoteObject) this, operations, 1, interfaceHash);
                try {
                    test.java.io.ObjectOutput out = call.getOutputStream();
                    out.writeInt($param_int_1);
                    out.writeObject($param_String_2);
                } catch (test.java.io.IOException e) {
                    throw new test.java.rmi.MarshalException("error marshalling arguments", e);
                }
                ref.invoke(call);
                ref.done(call);
            }
        } catch (test.java.lang.RuntimeException e) {
            throw e;
        } catch (test.java.rmi.RemoteException e) {
            throw e;
        } catch (test.java.lang.Exception e) {
            throw new test.java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }
}
